# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_db:
            entity:
                class: AppBundle:User
                property: mail
                        
    role_hierarchy:
        ROLE_BDE: [ROLE_USER]
        ROLE_BDS: [ROLE_USER]
        ROLE_ADMIN: [ROLE_BDE, ROLE_BDS]
                        
    encoders:
        AppBundle\Entity\User: bcrypt
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            
            form_login:
                login_path: app.login
                check_path: app.login
                
            logout:
                path: app.logout
                target: /
                
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }